server:
  port: 8081
  context-path: /springboot-demo

test:
  A: testA
  B: testB
test1: A

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8
    username: root
    data-password: 123456