server:
  port: 8081
  context-path: /springboot-demo

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/auth?useUnicode=true&characterEncoding=utf-8
  uesrname: root
  password: 123456
  maxIdel: 120
  maxWait: 100
  maxActive: 2335



test:
  A: testA
  B: testB
test1: A





